# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '59795337f073950857377d3604a60493'
  config.secret_key = '8e5f3fd672ea238347aaa6582e1ea7d2'
  config.default_from = 'support@b-wii.com'
	config.api_version = 'v3.1'
end
