---
development:
  cloud_name: dtxxp1unl
  api_key: ENV["CLOUD_API_KEY"]
  api_secret: ENV["CLOUD_SECRET"]
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: "dtxxp1unl"
  api_key: ENV["CLOUD_API_KEY"]
  api_secret: ENV["CLOUD_SECRET"]
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dtxxp1unl
  api_key: ENV["CLOUD_API_KEY"]
  api_secret: ENV["CLOUD_SECRET"]
  enhance_image_tag: true
  static_file_support: false
